#!/usr/bin/env python3
"""
generate_009_backfill.py — generate 369 UPDATE statements for migration 009_ward_hierarchy.sql

Reads data/gba_wards_2025.geojson and emits one UPDATE wards SET ... WHERE ward_number = N
AND ward_name = 'Name' statement per ward row. Run from the repo root:

    python3 scripts/generate_009_backfill.py > /tmp/009_backfill.sql

Each UPDATE includes all 8 hierarchy columns:
    zone_name, ro_division, aro_sub_division,
    assembly_constituency, assembly_constituency_no,
    parliamentary_constituency, mla_name, mp_name

AC→Lok Sabha mapping (Delimitation Commission of India):
    150: Yelahanka → Bangalore Rural
    151: K.R. Pura → Bangalore North
    152: Byatarayanapura → Bangalore North
    153: Yeshwanthapura → Bangalore North
    154: Rajarajeshwarinagar → Bangalore Rural
    155: Dasarahalli → Bangalore North
    156: Mahalakshmi Layout → Bangalore North
    157: Malleshwaram → Bangalore North
    158: Hebbal → Bangalore North
    159: Pulakeshinagar → Bangalore North
    160: Sarvagnanagar → Bangalore Central
    161: C.V. Raman Nagar → Bangalore Central
    162: Shivajinagar → Bangalore Central
    163: Shanthinagar → Bangalore Central
    164: Gandhinagara → Bangalore Central
    165: Rajajinagar → Bangalore Central
    166: Govindraj Nagar → Bangalore South
    167: Vijayanagar → Bangalore South
    168: Chamrajapet → Bangalore Central
    169: Chickpet → Bangalore South
    170: Basavanagudi → Bangalore South
    171: Padmanabanagar → Bangalore South
    172: B.T.M Layout → Bangalore South
    173: Jayanagar → Bangalore South
    174: Mahadevapura → Bangalore Central
    175: Bommanahalli → Bangalore South
    176: Bangalore South → Bangalore Rural
    177: Anekal → Bangalore Rural

MLA names (Karnataka 2023 Vidhan Sabha election results):
Source: bangalore.explocity.com/article/bangalore-city-mlas/

MP names (2024 Lok Sabha election results):
Source: Wikipedia AC composition tables + businesstoday.in 2024 results
"""

import json
import sys
import os

# ── Hardcoded lookup tables from 03-RESEARCH.md ───────────────────────────────

AC_TO_PC = {
    150: "Bangalore Rural",
    151: "Bangalore North",
    152: "Bangalore North",
    153: "Bangalore North",
    154: "Bangalore Rural",
    155: "Bangalore North",
    156: "Bangalore North",
    157: "Bangalore North",
    158: "Bangalore North",
    159: "Bangalore North",
    160: "Bangalore Central",
    161: "Bangalore Central",
    162: "Bangalore Central",
    163: "Bangalore Central",
    164: "Bangalore Central",
    165: "Bangalore Central",
    166: "Bangalore South",
    167: "Bangalore South",
    168: "Bangalore Central",
    169: "Bangalore South",
    170: "Bangalore South",
    171: "Bangalore South",
    172: "Bangalore South",
    173: "Bangalore South",
    174: "Bangalore Central",
    175: "Bangalore South",
    176: "Bangalore Rural",
    177: "Bangalore Rural",
}

AC_TO_MLA = {
    150: "S R Vishwanath",
    151: "B A Basavaraja",
    152: "Krishna Byregowda",
    153: "S T Somashekar",
    154: "Munirathna",
    155: "S Muniraju",
    156: "K Gopalaiah",
    157: "Dr C N Ashwathnarayan",
    158: "Suresha B S",
    159: "A C Srinivasa",
    160: "K J George",
    161: "S Raghu",
    162: "Rizwan Arshad",
    163: "N A Harris",
    164: "Dinesh Gundu Rao",
    165: "S Suresh Kumar",
    166: "Priya Krishna",
    167: "H R Gaviyappa",
    168: "BZ Zameer Ahmed Khan",
    169: "Uday B Garudachar",
    170: "Ravi Subramanya L A",
    171: "R Ashoka",
    172: "Ramalinga Reddy",
    173: "C K Ramamurthy",
    174: "Manjula S",
    175: "Satish Reddy M",
    176: "M Krishnappa",
    177: "V Shivanna",
}

PC_TO_MP = {
    "Bangalore North":   "Kumari Shobha Karandlaje",
    "Bangalore Central": "P.C. Mohan",
    "Bangalore South":   "Tejasvi Surya",
    "Bangalore Rural":   "Dr. C N Manjunath",
}

# ── Helpers ───────────────────────────────────────────────────────────────────

def escape_sql(s: str) -> str:
    """Escape single quotes for SQL string literals by doubling them."""
    return s.replace("'", "''")


def main():
    # Locate GeoJSON relative to script location (repo root)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)
    geojson_path = os.path.join(repo_root, "data", "gba_wards_2025.geojson")

    if not os.path.exists(geojson_path):
        print(f"ERROR: GeoJSON not found at {geojson_path}", file=sys.stderr)
        sys.exit(1)

    with open(geojson_path, encoding="utf-8") as f:
        data = json.load(f)

    features = data["features"]

    print(f"-- Generated by scripts/generate_009_backfill.py")
    print(f"-- Source: data/gba_wards_2025.geojson ({len(features)} features)")
    print(f"-- AC→PC mapping, MLA names, MP names from 03-RESEARCH.md")
    print()

    count = 0
    for feature in features:
        props = feature["properties"]

        ward_number    = int(props["ward_id"])
        ward_name      = props["ward_name"]
        zone_name      = props["zone_name"]
        ro_division    = props["RO_Division"]
        aro_sub_div    = props["ARO_ Sub Division"]
        ac_name        = props["ac"]
        ac_no          = int(props["ac_no"])

        # Lookup derived fields
        if ac_no not in AC_TO_PC:
            print(f"ERROR: ac_no={ac_no} not in AC_TO_PC mapping", file=sys.stderr)
            sys.exit(1)
        if ac_no not in AC_TO_MLA:
            print(f"ERROR: ac_no={ac_no} not in AC_TO_MLA mapping", file=sys.stderr)
            sys.exit(1)

        pc   = AC_TO_PC[ac_no]
        mla  = AC_TO_MLA[ac_no]
        mp   = PC_TO_MP[pc]

        print(f"UPDATE wards SET"
              f" zone_name = '{escape_sql(zone_name)}',"
              f" ro_division = '{escape_sql(ro_division)}',"
              f" aro_sub_division = '{escape_sql(aro_sub_div)}',"
              f" assembly_constituency = '{escape_sql(ac_name)}',"
              f" assembly_constituency_no = {ac_no},"
              f" parliamentary_constituency = '{escape_sql(pc)}',"
              f" mla_name = '{escape_sql(mla)}',"
              f" mp_name = '{escape_sql(mp)}'"
              f" WHERE ward_number = {ward_number} AND ward_name = '{escape_sql(ward_name)}';")
        count += 1

    print()
    print(f"-- Total: {count} UPDATE statements", file=sys.stderr)


if __name__ == "__main__":
    main()
